config/routes.rb
Rails.application.routes.draw do
  resources :lojas
  resources :pedidos
  resources :entregadors
  resources :pizzas
  get 'cardapio/_index'
  get 'menu_cliente/index'
  get 'clientes' => 'menu_adm#getClientes'
  get 'adms' => 'menu_adm#getAdms'

  resources :enderecos
  root 'home#index'
  devise_scope :user do
    get '/signup', to: 'users/registrations#new', as: :inactive_signup
    post '/users', to: 'users/registrations#create'
    get '/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session_path
    # get '/users', to: 'users/registrations#deleteOtherUser', as: :user_path
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :sabors
end

app/models/loja.rb
class Loja < ApplicationRecord
  validate :validarFuncionamento
  validates :abertura, presence: true
  validates :fechamento, presence: true

  def validarFuncionamento
    if !fechamento.nil? && !abertura.nil?
      if fechamento < abertura
        errors.add(:fechamento, "Hora de fechamento não pode ser antes da hora de abertura!")
      end
    end
  end
end 

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: %i[ show edit update destroy ]
  before_action :checkNewLoja, only: %i[ new index create destroy ]

  # GET /lojas or /lojas.json
  def index
    @lojas = Loja.all
  end

  def checkNewLoja
    redirect_to root_path, alert: "Não é possível criar uma nova Loja"
  end

  # GET /lojas/1 or /lojas/1.json
  def show
  end

  # GET /lojas/new
  def new
    @loja = Loja.new
  end

  # GET /lojas/1/edit
  def edit
  end

  # POST /lojas or /lojas.json
  def create
    @loja = Loja.new(loja_params)
    respond_to do |format|
      if @loja.save
        format.html { redirect_to @loja, notice: "Loja was successfully created." }
        format.json { render :show, status: :created, location: @loja }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lojas/1 or /lojas/1.json
  def update
    respond_to do |format|
      if @loja.update(loja_params)
        format.html { redirect_to @loja, notice: "Loja was successfully updated." }
        format.json { render :show, status: :ok, location: @loja }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lojas/1 or /lojas/1.json
  def destroy
    @loja.destroy
    respond_to do |format|
      format.html { redirect_to lojas_url, notice: "Loja was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loja
      @loja = Loja.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loja_params
      params.require(:loja).permit(:abertura, :fechamento)
    end
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/views/lojas/_form.html.erb
<%= form_with(model: loja) do |form| %>
  <% if loja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loja.errors.count, "error") %> prohibited this loja from being saved:</h2>

      <ul>
        <% loja.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :abertura %>
    <%= form.time_field :abertura, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :fechamento %>
    <%= form.time_field :fechamento, class: "form-control" %>
  </div>

  <br/>
  
  <div class="text-center">
    <%= form.submit class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/lojas/edit.html.erb
<h1 class="text-center">Editar Loja</h1>

<%= render 'form', loja: @loja %>

<br/>

<%= link_to 'Show', @loja, class: "btn btn-outline-dark" %> 
<%= link_to 'Back', root_path, class: "btn btn-outline-dark" %>

app/views/lojas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lojas</h1>

<table>
  <thead>
    <tr>
      <th>Abertura</th>
      <th>Fechamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lojas.each do |loja| %>
      <tr>
        <td><%= loja.abertura.strftime("%H:%M") %></td>
        <td><%= loja.fechamento.strftime("%H:%M") %></td>
        <td><%= link_to 'Show', loja %></td>
        <td><%= link_to 'Edit', edit_loja_path(loja) %></td>
        <td><%= link_to 'Destroy', loja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loja', new_loja_path %>

app/views/lojas/new.html.erb
<h1 class="text-center">New Loja</h1>

<%= render 'form', loja: @loja, class: "btn btn-outline-dark" %>

<%= link_to 'Back', lojas_path, class: "btn btn-outline-dark" %>

app/views/lojas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 style="color: #fd7e14" class="card-title">Abertura: <%= @loja.abertura.strftime("%H:%M") %></h5>
    <h5 style="color: #fd7e14" class="card-title">Fechamento: <%= @loja.fechamento.strftime("%H:%M") %></h6>
    <%= link_to 'Editar', edit_loja_path(@loja), class:"btn btn-outline-dark" %> 
    <%= link_to 'Voltar', root_path, class:"btn btn-outline-dark" %>  
  </div>
</div>