config/routes.rb
Rails.application.routes.draw do
  resources :lojas
  resources :pedidos
  resources :entregadors
  resources :pizzas
  get 'cardapio/_index'
  get 'menu_cliente/index'
  get 'clientes' => 'menu_adm#getClientes'
  get 'adms' => 'menu_adm#getAdms'

  resources :enderecos
  root 'home#index'
  devise_scope :user do
    get '/signup', to: 'users/registrations#new', as: :inactive_signup
    post '/users', to: 'users/registrations#create'
    get '/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session_path
    # get '/users', to: 'users/registrations#deleteOtherUser', as: :user_path
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :sabors
end

app/models/entregador.rb
class Entregador < ApplicationRecord
  has_many :pedidos
  validates :cpf, length: {is: 11}, presence: true, uniqueness: true,numericality: { only_integer: true }
  validates :nome, presence: true, length: {minimum: 3, too_short: "must have at least 3 characters", maximum: 30, too_long: "must have at maximum 30 characters" }
  validates :telefone, presence: true, numericality: { only_integer: true }, length: {minimum: 11, too_short: "must have at least numbers 11"}
end

app/controllers/entregadors_controller.rb
class EntregadorsController < ApplicationController
  before_action :set_entregador, only: %i[ show edit update destroy ]

  # GET /entregadors or /entregadors.json
  def index
    @entregadors = Entregador.all
  end

  # GET /entregadors/1 or /entregadors/1.json
  def show
  end

  # GET /entregadors/new
  def new
    @entregador = Entregador.new
  end

  # GET /entregadors/1/edit
  def edit
  end

  # POST /entregadors or /entregadors.json
  def create
    @entregador = Entregador.new(entregador_params)

    respond_to do |format|
      if @entregador.save
        format.html { redirect_to @entregador, notice: "Entregador was successfully created." }
        format.json { render :show, status: :created, location: @entregador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entregadors/1 or /entregadors/1.json
  def update
    respond_to do |format|
      if @entregador.update(entregador_params)
        format.html { redirect_to @entregador, notice: "Entregador was successfully updated." }
        format.json { render :show, status: :ok, location: @entregador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entregadors/1 or /entregadors/1.json
  def destroy
    @entregador.destroy
    respond_to do |format|
      format.html { redirect_to entregadors_url, notice: "Entregador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entregador
      @entregador = Entregador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entregador_params
      params.require(:entregador).permit(:nome, :telefone, :cpf)
    end
end

app/helpers/entregadors_helper.rb
module EntregadorsHelper
end

app/views/entregadors/_form.html.erb
<%= form_with(model: entregador) do |form| %>
  <% if entregador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entregador.errors.count, "error") %> prohibited this entregador from being saved:</h2>

      <ul>
        <% entregador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :nome, class: "form-control", placeholder: "Nome" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :telefone, class: "form-control", placeholder: "Telefone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :cpf, class: "form-control", placeholder: "CPF" %>
  </div>

  <div class="text-center">
    <%= form.submit class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/entregadors/edit.html.erb
<h1>Editar Entregador</h1>

<%= render 'form', entregador: @entregador %>

<%= link_to 'Show', @entregador, class: "btn btn-outline-dark" %> |
<%= link_to 'Back', entregadors_path %>

app/views/entregadors/index.html.erb
<h1 class="text-center">Entregadores</h1>

<table class="table bg-dark">
  <thead class="text-center table-dark">
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entregadors.each do |entregador| %>
      <tr class="text-center table-warning"> 
        <td><%= entregador.nome %></td>
        <td><%= entregador.telefone %></td>
        <td><%= entregador.cpf %></td>
        <td><%= link_to 'Show', entregador, class: "btn btn-outline-dark" %></td>
        <td><%= link_to 'Edit', edit_entregador_path(entregador), id:"e-#{entregador.cpf}", class: "btn btn-outline-dark" %></td>
        <td><%= button_to 'Destroy', entregador, method: :delete, data: { confirm: 'Are you sure?' }, id:"a-#{entregador.cpf}", class: "btn btn-outline-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Entregador', new_entregador_path, class: "btn btn-outline-dark" %> 
<%= link_to 'Home', root_path, class: "btn btn-outline-dark" %>

app/views/entregadors/new.html.erb
<h1 class="text-center">Novo Entregador</h1>

<%= render 'form', entregador: @entregador, class: "btn btn-outline-dark" %>

<br/>

<%= link_to 'Back', entregadors_path, class: "btn btn-outline-dark" %>

app/views/entregadors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 style="color: #fd7e14" class="card-title"><%= @entregador.nome %></h5>
    <h6 style="color: #000000" class="card-subtitle mb-2"><%= @entregador.telefone %></h6>
    <h6 style="color: #000000" class="card-subtitle mb-2"><%= @entregador.cpf %></h6>
    <%= link_to 'Editar', edit_entregador_path(@entregador), class:"btn btn-outline-dark" %> 
    <%= link_to 'Voltar', entregadors_path, class:"btn btn-outline-dark" %>  
  </div>
</div>