config/routes.rb
Rails.application.routes.draw do
  resources :lojas
  resources :pedidos
  resources :entregadors
  resources :pizzas
  get 'cardapio/_index'
  get 'menu_cliente/index'
  get 'clientes' => 'menu_adm#getClientes'
  get 'adms' => 'menu_adm#getAdms'

  resources :enderecos
  root 'home#index'
  devise_scope :user do
    get '/signup', to: 'users/registrations#new', as: :inactive_signup
    post '/users', to: 'users/registrations#create'
    get '/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session_path
    # get '/users', to: 'users/registrations#deleteOtherUser', as: :user_path
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :sabors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :user

  validates :cep, presence: true, numericality: { only_integer: true }, length: {is: 8}
  validates :cidade, presence: true, length: {minimum: 4, too_short: "Must have at least 4 characters!"}
  validates :bairro, presence: true, length: {minimum: 4, too_short: "Must have at least 4 characters!"}
  validates :logradouro, presence: true, length: {minimum: 4, too_short: "Must have at least 4 characters!"}
  validates :complemento, length: {maximum:50, too_long: "Must have at maximum 50 characters!"}

end

app/models/entregador.rb
class Entregador < ApplicationRecord
  has_many :pedidos
  validates :cpf, length: {is: 11}, presence: true, uniqueness: true,numericality: { only_integer: true }
  validates :nome, presence: true, length: {minimum: 3, too_short: "must have at least 3 characters", maximum: 30, too_long: "must have at maximum 30 characters" }
  validates :telefone, presence: true, numericality: { only_integer: true }, length: {minimum: 11, too_short: "must have at least numbers 11"}
end

app/models/loja.rb
class Loja < ApplicationRecord
  validate :validarFuncionamento
  validates :abertura, presence: true
  validates :fechamento, presence: true

  def validarFuncionamento
    if !fechamento.nil? && !abertura.nil?
      if fechamento < abertura
        errors.add(:fechamento, "Hora de fechamento não pode ser antes da hora de abertura!")
      end
    end
  end
end 

app/models/pedido.rb
class Pedido < ApplicationRecord 
  has_one :pizza , dependent: :destroy
  accepts_nested_attributes_for :pizza, allow_destroy: true, reject_if: :all_blank

  belongs_to :endereco
  belongs_to :entregador

  validates_associated :pizza
  validates_presence_of :pizza, :message => "Preencha os campos de pizza"

  validates :endereco_id, presence: true
  validates :entregador_id, presence: true
  validates :quantidadePizzas, presence: true
  validates :contato, presence: true, numericality: { only_integer: true },  length: {is: 11}
  validates :observacao, length: { maximum: 40, too_long: "must have at maximum 40 characters" }
  validates :nomeDestinatario, presence: true, length: {minimum: 3, too_short: "must have at least 3 characters "}, length: { maximum: 30, too_long: "must have at maximum 30 characters" }
end

app/models/pizza.rb
class Pizza < ApplicationRecord
    belongs_to :pedido
    has_many :sabor

    # validate :checarSabores
    validates :tamanho, presence: true
    validates :observacao, length: { maximum: 40, too_long: "must have at maximum 40 characters" }
end

app/models/sabor.rb
class Sabor < ApplicationRecord
  validates :descricao, presence: true, uniqueness: true, length: {minimum: 3, too_short: "Must have at least 3 characters!"}
  validates :preco, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :enderecos, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:cpf]

  validates :cpf, length: {is: 11}, presence: true, uniqueness: true,numericality: { only_integer: true }
  validates :nome, presence: true, length: {minimum: 3, too_short: "must have at least 3 characters "}, length: { maximum: 30, too_long: "must have at maximum 30 characters" }
  validates :telefone, presence: true, numericality: { only_integer: true }, length: {minimum: 11, too_short: "must have at least numbers 11"}
  validates :password_confirmation, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @loja = Loja.first
    end

end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: %i[ show edit update destroy ]
  before_action :checkNewLoja, only: %i[ new index create destroy ]

  # GET /lojas or /lojas.json
  def index
    @lojas = Loja.all
  end

  def checkNewLoja
    redirect_to root_path, alert: "Não é possível criar uma nova Loja"
  end

  # GET /lojas/1 or /lojas/1.json
  def show
  end

  # GET /lojas/new
  def new
    @loja = Loja.new
  end

  # GET /lojas/1/edit
  def edit
  end

  # POST /lojas or /lojas.json
  def create
    @loja = Loja.new(loja_params)
    respond_to do |format|
      if @loja.save
        format.html { redirect_to @loja, notice: "Loja was successfully created." }
        format.json { render :show, status: :created, location: @loja }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lojas/1 or /lojas/1.json
  def update
    respond_to do |format|
      if @loja.update(loja_params)
        format.html { redirect_to @loja, notice: "Loja was successfully updated." }
        format.json { render :show, status: :ok, location: @loja }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lojas/1 or /lojas/1.json
  def destroy
    @loja.destroy
    respond_to do |format|
      format.html { redirect_to lojas_url, notice: "Loja was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loja
      @loja = Loja.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loja_params
      params.require(:loja).permit(:abertura, :fechamento)
    end
end

app/controllers/menu_adm_controller.rb
class MenuAdmController < ApplicationController

    def index
        @loja = Loja.first
    end
    
    def getClientes
        @clientes = User.where(adm: nil)
    end

    def getAdms
        @adms = User.where(adm: true)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cardapio_helper.rb
module CardapioHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/entregadors_helper.rb
module EntregadorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/menu_adm_helper.rb
module MenuAdmHelper
end

app/helpers/menu_cliente_helper.rb
module MenuClienteHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/sabors_helper.rb
module SaborsHelper
end

app/views/menu_adm/_index.html.erb
<h1>Menu</h1>
<h1>Bem vindo ao Sistema</h1>
<h2>Bem Vindo Administrador</h2>
<% link_to "Pedidos", pedidos_path %>
<% link_to "Sabores", sabors_path %>
<% link_to "Clientes", clientes_path %>
<% link_to "Administradores", adms_path %>
<% link_to "Entregadores", entregadors_path %>
<% link_to "Loja", @loja %>
<% link_to 'Editar login', edit_user_registration_path%>
<% link_to 'Sair', destroy_user_session_path, method: :delete%>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Pedidos</h5>
                    <li><%= link_to 'Index', pedidos_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Fazer um Pedido', new_pedido_path, class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Endereços</h5>
                    <li><%= link_to 'Cadastrar novo endereço', new_endereco_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Index Endereços', enderecos_path, class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Entregadores</h5>
                    <li><%= link_to 'Index Entregadores', entregadors_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Cadastrar novo entregador', new_entregador_path, class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Sabores</h5>
                    <li><%= link_to 'Index Sabores', sabors_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Cadastrar novo sabor', new_sabor_path, class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Clientes</h5>
                    <li><%= link_to 'Index Clientes', clientes_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Cadastrar novo cliente', '/signup', class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Administradores</h5>
                    <li><%= link_to 'Index Administradores', adms_path, class: "dropdown-item" %></li> 
                    <li><%= link_to 'Cadastrar novo administrador', '/signup', class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>


        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 style="color: #fd7e14" class="card-title">Loja</h5>
                    <li><%= link_to 'Show Loja', loja_path(1), class: "dropdown-item" %></li> 
                    <li><%= link_to 'Editar Abertura/Fechamento', edit_loja_path(1), class: "dropdown-item" %></li>  
                </div>
            </div>
        </div>

    </div>

</div>

app/views/menu_adm/getAdms.html.erb
<h1 class="text-center">Administradores</h1>

<table class="table bg-dark">
  <thead class="text-center table-dark">
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>CPF</th>
      <th>Telefone</th>
    </tr>
  </thead>
  <tbody>
    <% @adms.each do |adm| %>
      <tr class="text-center table-warning">
        <td><%= adm.nome %></td>
        <td><%= adm.email %></td>
        <td><%= adm.cpf %></td>
        <td><%= adm.telefone %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Novo Administrador", new_user_registration_path, class: "btn btn-outline-dark" %>
<%= link_to "Back", root_path, class: "btn btn-outline-dark" %>

app/views/menu_adm/getClientes.html.erb
<h1 class="text-center">Clientes</h1>

<table class="table bg-dark">
  <thead class="text-center table-dark">
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>CPF</th>
      <th>Telefone</th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr class="text-center table-warning">
        <td><%= cliente.nome %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.telefone %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Novo Cliente", new_user_registration_path, class: "btn btn-outline-dark" %>
<%= link_to "Back", root_path, class: "btn btn-outline-dark" %>