config/routes.rb
Rails.application.routes.draw do
  resources :lojas
  resources :pedidos
  resources :entregadors
  resources :pizzas
  get 'cardapio/_index'
  get 'menu_cliente/index'
  get 'clientes' => 'menu_adm#getClientes'
  get 'adms' => 'menu_adm#getAdms'

  resources :enderecos
  root 'home#index'
  devise_scope :user do
    get '/signup', to: 'users/registrations#new', as: :inactive_signup
    post '/users', to: 'users/registrations#create'
    get '/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session_path
    # get '/users', to: 'users/registrations#deleteOtherUser', as: :user_path
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :sabors
end

app/models/pedido.rb
class Pedido < ApplicationRecord 
  has_one :pizza , dependent: :destroy
  accepts_nested_attributes_for :pizza, allow_destroy: true, reject_if: :all_blank

  belongs_to :endereco
  belongs_to :entregador

  validates_associated :pizza
  validates_presence_of :pizza, :message => "Preencha os campos de pizza"

  validates :endereco_id, presence: true
  validates :entregador_id, presence: true
  validates :quantidadePizzas, presence: true
  validates :contato, presence: true, numericality: { only_integer: true },  length: {is: 11}
  validates :observacao, length: { maximum: 40, too_long: "must have at maximum 40 characters" }
  validates :nomeDestinatario, presence: true, length: {minimum: 3, too_short: "must have at least 3 characters "}, length: { maximum: 30, too_long: "must have at maximum 30 characters" }
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]
  before_action :checkStatus, only: %i[ update edit destroy ]
  before_action :checkHorario, only: %i[ update edit destroy create new ]
  before_action :authenticate_user!

  # GET /pedidos or /pedidos.json
  def index
    if current_user.adm?
      @pedidos = Pedido.all
    else
      @pedidos = Pedido.where(cpfDestinatario: current_user.cpf)
    end
  end

  def checkHorario
    loja = Loja.first
    if (Time.new.strftime("%H:%M") < loja.abertura.strftime("%H:%M") || Time.new.strftime("%H:%M") > loja.fechamento.strftime("%H:%M")) && !current_user.nil? && !current_user.adm?
      redirect_to root_path, alert: "A loja não está em funcionamento nesse horário"
    end
  end

  def checkStatus
    unless current_user.adm
      if @pedido.status != "Visto" && @pedido.status !=  "Esperando Visualização"
        redirect_to @pedido, alert: "O pedido não pode mais ser editado."
      end
    end
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
    @entregador = Entregador.find_by(id: @pedido.entregador_id).nome
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
    @pedido.build_pizza
  end

  # GET /pedidos/1/edit
  def edit
  end


  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)
    @pedido.cpfDestinatario = current_user.cpf
    @pedido.nomeDestinatario ||= current_user.nome
    @pedido.contato ||= current_user.telefone

    unless @pedido.pizza.nil?
      # Associação dos sabores e tamanhos escolhidos
      definir_preco_da_pizza

      definir_quantidade_de_fatias

      @pedido.precoTotal = @pedido.quantidadePizzas * @pedido.pizza.preco

    end

    @pedido.status = "Esperando Visualização"
    @pedido.entregador_id = Entregador.first.id

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
        @pedido.build_pizza
      end
    end
  end

  def definir_preco_da_pizza
    if !@pedido.pizza.sabor1_id.nil? && !@pedido.pizza.sabor2_id.nil?
      @pedido.pizza.preco = (Sabor.find_by(id: @pedido.pizza.sabor1_id).preco / 2) + (Sabor.find_by(id: @pedido.pizza.sabor2_id).preco / 2)
      @pedido.pizza.preco *= @pedido.pizza.tamanho
    elsif !@pedido.pizza.sabor1_id.nil? && @pedido.pizza.sabor2_id.nil?
      @pedido.pizza.preco = Sabor.find_by(id: @pedido.pizza.sabor1_id).preco * @pedido.pizza.tamanho

    elsif @pedido.pizza.sabor1_id.nil? && !@pedido.pizza.sabor2_id.nil?
      @pedido.pizza.preco = Sabor.find_by(id: @pedido.pizza.sabor2_id).preco * @pedido.pizza.tamanho
    end
  end

  def definir_quantidade_de_fatias
    if @pedido.pizza.tamanho == 1
      @pedido.pizza.fatias = 6
    elsif @pedido.pizza.tamanho == 1.5
      @pedido.pizza.fatias = 8
    elsif @pedido.pizza.tamanho == 1.8
      @pedido.pizza.fatias = 12
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
    
    unless @pedido.pizza.nil?
      # Associação dos sabores e tamanhos escolhidos
      definir_preco_da_pizza

      definir_quantidade_de_fatias

      precoTotal = @pedido.quantidadePizzas * @pedido.pizza.preco
      @pedido.update(precoTotal: precoTotal)
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.update(status: "Cancelado")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:endereco_id, :entregador_id, :precoTotal, :status, :quantidadePizzas, :observacao, :nomeDestinatario, :contato, :cpfDestinatario, :pizza_attributes => [:tamanho, :fatias, :preco, :observacao, :sabor1_id, :sabor2_id])
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>

  <%=  form.fields_for :pizza do |ff| %>
    <div class='field'>
      <% tamanhos = {"Tamanho G" => 1.8, "Tamanho M" => 1.5, "Tamanho P" => 1} %>
      <fieldset>
        <% lista = tamanhos.sort %>
        <% lista.each do |tamanho| %>
          <%= ff.radio_button :tamanho, tamanho[1] %>
          <label for="<%= tamanho[1] %>" ><%= tamanho[0] %> </label>
        <% end %>
      </fieldset>
    </div>

    <div class="field">
      <%= ff.collection_select(:sabor1_id, Sabor.all, :id, :descricao, include_blank: "Escolha um sabor") %>
    </div>

    <div class="field">
      <%= ff.collection_select(:sabor2_id, Sabor.all, :id, :descricao, include_blank: "Escolha um sabor") %>
    </div>
    <br/>

    <div class="field form-group">
      <%= ff.number_field :fatias, disabled: true, class: "form-control", placeholder: "Fatias" %>
    </div>
    <br/>

    <div class="field form-group">
      <%= ff.text_field :preco, disabled: true, class: "form-control", placeholder: "Preço" %>
    </div>
    <br/>

    <div class="field form-group">
      <%= ff.text_area :observacao, class: "form-control", placeholder: "Descrição" %>
    </div>
    <br/>
  <% end %>

  <h1 class="text-center"> Informações do Pedido </h1>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.collection_select(:endereco_id, current_user.enderecos, :id, :logradouro, include_blank: "Enderecos")%>
  </div>

  <br/>

  <% if current_user.adm? %>
    <div class="field">
      <%= form.collection_select(:entregador_id, Entregador.all, :id, :nome, include_blank: "Entregador")%>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.text_field :precoTotal, disabled: true, class: "form-control", placeholder: "Preço Total" %>
  </div>


  <div class="field form-group">
    <%= form.number_field :quantidadePizzas, min: 1, max: 10, value: 1, :class => "form-control", include_blank: "Quantidade de Pizzas" %>
  </div>

  <div class="field form-group">
    <%= form.text_area :observacao, class: "form-control", placeholder: "Observação"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :nomeDestinatario,  value: current_user.nome, :class => "form-controller", placeholder: "Nome Destinatário"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :contato, value: current_user.telefone, :class => "form-controller", placeholder: "Contato"%>
  </div>

  <% if current_user.adm? %>
    <div class="field">
      <% status = {"Esperando Visualização" => "Esperando Visualização", "Visto" => "Visto", "Em preparo" => "Em preparo", "Saiu para entrega" => "Saiu para entrega", "Entregue" => "Entregue", "Cancelado" => "Cancelado"} %>
      <fieldset>
        <h5>Status</h5>
        <% lista = status %>
        <% lista.each do |status| %>
          <%= form.radio_button :status, status[1] %>
          <label for="<%= status[1] %>" ><%= status[0] %> </label><br/>
        <% end %>
      </fieldset>
    </div>
  <% end %>

  <div class="text-center">
    <%= form.submit class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/pedidos/_form_adm.html.erb
<%= form_with(model: pedido) do |form| %>

  <%=  form.fields_for :pizza do |ff| %>
      
    <div class='field'>
      <% tamanhos = {"Tamanho G" => 1.8, "Tamanho M" => 1.5, "Tamanho P" => 1} %>
      <fieldset>
        <% lista = tamanhos.sort %>
        <% lista.each do |tamanho| %>
          <%= ff.radio_button :tamanho, tamanho[1] %>
          <label for="<%= tamanho[1] %>" ><%= tamanho[0] %> </label>
        <% end %>
      </fieldset>
    </div>


    <div class="field">
      <%= ff.label :sabor1 %>
      <%= ff.collection_select(:sabor1_id, Sabor.all, :id, :descricao, include_blank: "Escolha um sabor") %>
    </div>

    <div class="field">
      <%= ff.label :sabor2 %>
      <%= ff.collection_select(:sabor2_id, Sabor.all, :id, :descricao, include_blank: "Escolha um sabor") %>
    </div>
    <br/>

    <div class="field">
      <%= ff.label :fatias %>
      <%= ff.number_field :fatias, disabled: true, class: "form-control", placeholder: "Fatias"%>
    </div>
    <br/>

    <div class="field">
      <%= ff.label :preco %>
      <%= ff.text_field :preco, disabled: true, class: "form-control", placeholder: "Preço" %>
    </div>
    <br/>

    <div class="field">
      <%= ff.label :observacao %>
      <%= ff.text_area :observacao, disabled: true, class: "form-control", placeholder: "Descrição" %>
    </div>
    <br/>
  <% end %>

  <h1 class="text-center"> Informações do Pedido </h1>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.adm? %>
    <div class="field">
      <%= form.label :entregador_id %>
      <%= form.collection_select(:entregador_id, Entregador.all, :id, :nome, include_blank: "Entregador") %>
    </div>
  <% end %>
 

  <div class="field">
    <%= form.label :precoTotal %>
    <%= form.text_field :precoTotal, disabled: true, class: "form-control", placeholder: "Preço Total" %>
  </div>


  <div class="field">
    <%= form.label :quantidadePizzas %>
    <%= form.number_field :quantidadePizzas, min: 1, max: 10, value: @pedido.quantidadePizzas, :class => "form-controller", disabled: true, placeholder: "Quantidade de Pizzas" %>
  </div>

  <div class="field">
    <%= form.label :observacao %>
    <%= form.text_area :observacao, class: "form-control", placeholder: "Observação" %>
  </div>

  <div class="field">
    <%= form.label :nomeDestinatario %>
    <%= form.text_field :nomeDestinatario, disabled: true, class: "form-control", placeholder: "Observação"%>
  </div>

  <div class="field">
    <%= form.label :contato %>
    <%= form.text_field :contato, disabled: true, class: "form-control", placeholder: "Observação"%>
  </div>

  <% if current_user.adm? %>
    <div class="text-center">
      <% status = {"Esperando Visualização" => "Esperando Visualização", "Visto" => "Visto", "Em preparo" => "Em preparo", "Saiu para entrega" => "Saiu para entrega", "Entregue" => "Entregue", "Cancelado" => "Cancelado"} %>
      <fieldset>
        <h5>Status</h5>
        <% lista = status %>
        <% lista.each do |status| %>
          <%= form.radio_button :status, status[1] %>
          <label for="<%= status[1] %>" ><%= status[0] %> </label><br/>
        <% end %>
      </fieldset>
    </div>
  <% end %>

  <div class="text-center">
    <%= form.submit %>
  </div>
   
<% end %>

app/views/pedidos/edit.html.erb
<h1 class="text-center">Editar Pedido</h1>

<%if !current_user.adm %>
    <%= render 'form', pedido: @pedido %>
<%else%>
    <%= render 'form_adm', pedido: @pedido %>
<%end%>

<%= link_to 'Show', @pedido, class: "btn btn-outline-dark" %> |
<%= link_to 'Back', pedidos_path, class: "btn btn-outline-dark" %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Pedidos</h1>

<table class="table bg-dark">

  <thead class="text-center table-dark">
    <tr>
      <th>ID</th>
      <th>Endereco</th>
      <th>Entregador</th>
      <th>Precototal</th>
      <th>Status</th>
      <th>QuantidadePizzas</th>
      <th>Observacao</th>
      <th>Nomedestinatario</th>
      <th>Contato</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr class="text-center table-warning">
        <td>p.<%= pedido.id %></td>
        <td><%= pedido.endereco.logradouro %></td>
        <td><%= pedido.entregador_id %></td>
        <td><%= pedido.precoTotal %></td>
        <td><%= pedido.status %></td>
        <td><%= pedido.quantidadePizzas %></td>
        <td><%= pedido.observacao %></td>
        <td><%= pedido.nomeDestinatario %></td>
        <td><%= pedido.contato %></td>
        <td><%= link_to 'Show', pedido, id:"S-#{pedido.id}", class: "btn btn-outline-dark" %></td>
        
        <%if current_user.adm%>
          <td><%= link_to 'Edit', edit_pedido_path(pedido), id:"e-#{pedido.id}", class: "btn btn-outline-dark" %></td>
          <td><%= link_to 'Destroy', pedido,  method: :delete, data: { confirm: 'Are you sure?' }, id:"D-#{pedido.id}", class: "btn btn-outline-dark" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Fazer um Pedido', new_pedido_path, class: "btn btn-outline-dark" %> 
<%= link_to 'Home', root_path, class: "btn btn-outline-dark" %>

app/views/pedidos/new.html.erb
<h1 class="text-center">Monte sua Pizza</h1>

<%= render 'form', pedido: @pedido, pizza: @pizza, class: "btn btn-outline-dark" %>

<%= link_to 'Voltar', pedidos_path, class: "btn btn-outline-dark" %>

app/views/pedidos/show.html.erb
<% if !@pedido.pizza.sabor1_id.nil? && !@pedido.pizza.sabor2_id.nil? %>
  <% s1 = Sabor.find_by(id: @pedido.pizza.sabor1_id)%>
  <% s2 = Sabor.find_by(id: @pedido.pizza.sabor2_id)%>
<% elsif !@pedido.pizza.sabor1_id.nil? && @pedido.pizza.sabor2_id.nil? %>
  <% s1 = Sabor.find_by(id: @pedido.pizza.sabor1_id)%>
<% else %>
  <% s2 = Sabor.find_by(id: @pedido.pizza.sabor2_id)%>
<%end%>

<% e = Endereco.find_by(id: @pedido.endereco_id)%>



<div class="card" style="width: 18rem;">
  <div class="card-body">
  <h5 style="color: #fd7e14" class="card-title">ID: <%= @pedido.id %></h5>
    <h5 style="color: #fd7e14" class="card-title"><%= @pedido.quantidadePizzas %> X </h5>
    <% if !@pedido.pizza.sabor1_id.nil? && !@pedido.pizza.sabor2_id.nil? %>
      <h5 style="color: #fd7e14" class="card-title"><%= s1.descricao %></h5> | <h5 style="color: #fd7e14" class="card-title"><%= s2.descricao %> </h5>
    <% elsif !@pedido.pizza.sabor1_id.nil? && @pedido.pizza.sabor2_id.nil? %>
      <h5 style="color: #fd7e14" class="card-title"><%= s1.descricao %> </h5>
    <% else %>
      <h5 style="color: #fd7e14" class="card-title"><%= s2.descricao %> </h5>
    <%end%>
    <h6 style="color: #000000" class="card-subtitle mb-2"><%= @pedido.nomeDestinatario %>, <%= @pedido.contato %> </h6>
    <h6 style="color: #000000" class="card-subtitle mb-2">Endereço: <%= e.logradouro %></h6>
    <%if current_user.adm%>
      <h6 style="color: #000000" class="card-subtitle mb-2"><%= @entregador %></h6>
    <%end%>
    <h6 style="color: #000000" class="card-subtitle mb-2"> Preço total: R$ <%= @pedido.precoTotal %></h6>
    <h6 style="color: #000000" class="card-subtitle mb-2">Observação: <%= @pedido.observacao %></h6>
    <h6 style="color: #000000" class="card-subtitle mb-2"><%= @pedido.status %></h6>
    <%if !current_user.adm && (@pedido.status == "Esperando Visualização" || @pedido.status == "Visto")%>
      <%= link_to 'Editar', edit_pedido_path(@pedido), class:"btn btn-outline-dark" %> |
      <%= link_to 'Destroy', @pedido, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %> | 
    <%end%>
    <%= link_to 'Voltar', pedidos_path, class:"btn btn-outline-dark" %>  
  </div>
</div>